services:
  task-queue:
    container_name: task-queue
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # celery-worker:
    #   container_name: celery-worker
    #   build: .
    #   command: celery -A twaice_rte.app.core.celery_app worker --loglevel=info
    #   volumes:
    #     - .:/app
    # environment:
    #   - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    #   - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    # depends_on:
    #   - task-queue
    # api:
    #   container_name: twaice-rte-api
    #   build: .
    #   ports:
    #     - 8000:8000
    #   volumes:
    #     - .:/usr/src/app
