services:
  task-queue:
    container_name: task-queue
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  api:
    container_name: twaice-rte-api
    command: poetry run poe serve:dev
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - task-queue

  celery-worker:
    container_name: celery-worker
    build: .
    command: poetry run poe serve:tasks
    volumes:
      - .:/usr/src/app
    depends_on:
      - api
