services:
  task-queue:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
      # api:
      #   container_name: twaice-rte-api
      #   build: .
      #   ports:
      #     - 8000:8000
      #   volumes:
      #     - .:/usr/src/app
      # task-queue:
      #   image: redis:6.2-alpine
      #   restart: always
      #   ports:
      #     - '6379:6379'
      #       command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      #       volumes:
      #         - task-queue-volume:/data
      #     volumes:
      #       task-queue-volume:

      # pybase-db:
      #   container_name: pybase-db
      #   build:
      #     context: ./pybase/db
      #     dockerfile: Dockerfile
      #   expose:
      #     - 5432
      #   environment:
      #     - POSTGRES_USER=postgres
      #     - POSTGRES_PASSWORD=postgres
